use_frameworks!

target 'SnackBar.swift_Example' do
  pod 'SnackBar.swift', :path => '../'

  target 'SnackBar.swift_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
